### ISSUE TITLE
CKAN 2.9: Uncaught ReferenceError: ckan is not defined

### ISSUE THREAD

**Issue by KatiRG** [ongov/ckanext-ontario_theme#246]
This error occurs in CKAN 2.9 when the ckan module in [ontario_theme_lock_if_odc.js](https://github.com/ongov/ckanext-ontario_theme/blob/ckan_2.9_upgrade/ckanext/ontario_theme/fanstatic/internal/ontario_theme_lock_if_odc.js) is called when creating a new dataset. Error not present in CKAN 2.8.

Note: the [example in the CKAN docs](https://docs.ckan.org/en/2.9/theming/javascript.html) also gives the same error that ckan is not defined.

**Comment by KatiRG** [comment]
Somehow, reference to CKAN's [ckan.js](https://github.com/ckan/ckan/blob/master/ckan/public-bs3/base/javascript/module.js) is missing from `ontario_theme`, and I don't know where to add it. I have tried via the `webassets.yml` file but with no success. The only way so far I can get `ckan.module` to work is to paste the actual [ckan.js](https://github.com/ckan/ckan/blob/master/ckan/public-bs3/base/javascript/module.js) code (minus the references to `i18`) in the [ontario_theme_lock_if_odc.js](https://github.com/ongov/ckanext-ontario_theme/blob/ckan_2.9_modulebug/ckanext/ontario_theme/fanstatic/internal/ontario_theme_lock_if_odc.js) script itself.

Until this is further resolved, I have converted the `ckan.module` into a jQuery fn which will at least allow this script to run.

**Comment by KatiRG** [comment]
Update: it is `module.js` that was missing, but it turns out that `module.js` is bundled inside of `main.js` (see https://github.com/ckan/ckan/blob/master/ckan/public-bs3/base/javascript/webassets.yml). Since`main.js` was getting loaded _after_ `ontario_theme_lock_if_odc.js`, the solution was to preload `main.js` in the `webassets.yml` file:
```
ontario_theme_lock_if_odc_js:
  filters: rjsmin
  contents: ontario_theme_lock_if_odc.js
  output: ontario_theme/%(version)s_ontario_theme_lock_if_odc.js
  extra:
    preload:
      - vendor/jquery
      - base/main
```
